spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: org.apache.tomcat.jdbc.pool.DataSource

mybatis:
  mapper-locations: classpath:mappings/*Mapper.xml

blog:
  host: http://localhost:8080
  activationUrl: /user/activate/%s/%s